// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uftblhkwilewgozzqjaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdGJsaGt3aWxld2dvenpxamFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDY0OTEsImV4cCI6MjA3MjE4MjQ5MX0.DltytqfKMykkxIL8aivga7Y7yBzU7GD4_foFfndJD2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});